paramsLKP = [
{"count":313,"code":"QD","name":"Daily Mean Total Discharge (cfs)"},
{"count":293,"code":"PU","name":"Total Water Year Precipitation (inches)"},
{"count":290,"code":"GD","name":"Daily Mean Gage Height (feet)"},
{"count":232,"code":"MX","name":"Daily Maximum Air Temperature (degrees F)"},
{"count":232,"code":"MN","name":"Daily Minimum Air Temperature (degrees F)"},
{"count":232,"code":"MM","name":"Daily Mean Air Temperature (degrees F)"},
{"count":212,"code":"HH","name":"Gage Height Shift (feet)"},
{"count":187,"code":"SE","name":"Snow Water Equivalent (inches)"},
{"count":163,"code":"PP","name":"Total Precipitation (inches per day)"},
{"count":100,"code":"QJ","name":"Daily Mean Canal Discharge (cfs)"},
{"count":99,"code":"GJ","name":"Daily Mean Canal Gage Height (feet)"},
{"count":94,"code":"FB","name":"Reservoir Forebay Elevation (feet)"},
{"count":93,"code":"AF","name":"Reservoir Storage Content (acre-feet)"},
{"count":64,"code":"AF_AVG","name":"Reservoir Historic Average Content (acre-feet)"},
{"count":60,"code":"IN","name":"Daily Mean Computed Inflow (cfs)"},
{"count":40,"code":"SE_PCT","name":"Snow Water Equivalent Percent of Average (percent)"},
{"count":36,"code":"WD","name":"Wind Direction (degrees)"},
{"count":36,"code":"UA","name":"Daily Mean Wind Speed (mph)"},
{"count":36,"code":"HJ","name":"Canal Shift (feet)"},
{"count":33,"code":"QRD","name":"Daily Mean River Discharge (cfs)"},
{"count":32,"code":"WY","name":"Daily Mean Water Temperature (degrees C)"},
{"count":32,"code":"WN","name":"Daily Minimum Water Temperature (degrees C)"},
{"count":32,"code":"WM","name":"Daily Maximum Water Temperature (degrees C)"},
{"count":29,"code":"TA","name":"Mean Daily Humidity (percent)"},
{"count":28,"code":"WZ","name":"Daily Mean Water Temperature (degrees F)"},
{"count":28,"code":"WL","name":"Daily Minimum Water Temperature (degrees F)"},
{"count":28,"code":"WK","name":"Daily Maximum Water Temperature (degrees F)"},
{"count":23,"code":"SR","name":"Solar Radiation (Langleys per day)"},
{"count":23,"code":"SE_AVG","name":"Snow Water Equivalent Average (inches)"},
{"count":22,"code":"YM","name":"Daily Mean Air Temperature, Dew Point (degrees F)"},
{"count":21,"code":"TG","name":"Growing Degree Days (degrees F)"},
{"count":20,"code":"WR","name":"Daily Wind Run (miles)"},
{"count":20,"code":"WGD","name":"Daily Peak Wind Gust (mph)"},
{"count":20,"code":"ET","name":"Modified Penman ETr (inches)"},
{"count":20,"code":"EH","name":"Pan Evaporation (inches)"},
{"count":16,"code":"QSD","name":"Daily Mean Spillway Discharge (cfs)"},
{"count":14,"code":"RBD","name":"Daily Mean Gate #2 Opening (feet)"},
{"count":14,"code":"FB_OPAV","name":"Operation Model Average Forebay Elevation (feet)"},
{"count":14,"code":"AF_PCT","name":"Reservoir Storage Percent of Average (percent)"},
{"count":14,"code":"AF_OPAV","name":"Operation Model Average Storage Content (acre-feet)"},
{"count":14,"code":"AF_%FUL","name":"Reservoir Storage Percent of Full (percent)"},
{"count":13,"code":"EV","name":"Daily Evaporation (acre-feet)"},
{"count":11,"code":"EVF","name":"Daily Evaporation Factor (feet)"},
{"count":10,"code":"RDD","name":"Daily Mean Gate #4 Opening (feet)"},
{"count":8,"code":"GJ_B","name":"Canal Gage Height, Downstream, Shift (feet)"},
{"count":8,"code":"CHSTOR","name":"Change in Storage (acre-feet)"},
{"count":7,"code":"RAD","name":"Daily Mean Gate #1 Opening (feet)"},
{"count":7,"code":"QEV","name":"Daily Mean Evaporation Rate (cfs)"},
{"count":7,"code":"IN30PCT","name":"Daily Inflow Percent of 30 Year Average (percent)"},
{"count":7,"code":"IN30AVG","name":"Last 30 years average inflow (cfs)"},
{"count":7,"code":"BH","name":"Barometric Pressure (mm of Hg)"},
{"count":6,"code":"VT","name":"Total Daily Energy Generation (mwh)"},
{"count":6,"code":"QX","name":"Daily Maximum Discharge (cfs)"},
{"count":6,"code":"QN","name":"Daily Minimum Discharge (cfs)"},
{"count":5,"code":"WE","name":"Water Specific Conductance (microsiemens per centimeter)"},
{"count":4,"code":"QROD","name":"Daily Mean Regulating Outlet Discharge (cfs)"},
{"count":4,"code":"QJS","name":"Daily South Canal Discharge (cfs)"},
{"count":4,"code":"QJN","name":"Daily North Canal Discharge (cfs)"},
{"count":4,"code":"QED","name":"Daily Mean Power Turbine Discharge (cfs)"},
{"count":3,"code":"TD","name":"Daily Mean Tailwater Elevation (feet)"},
{"count":3,"code":"RCD","name":"Daily Mean Gate #3 Opening (feet)"},
{"count":3,"code":"QZD","name":"Mean Daily Municipal Use Discharge (cfs)"},
{"count":3,"code":"QUD","name":"Daily Mean Computed Unregulated Flow (cfs)"},
{"count":3,"code":"QJ_TOT","name":"Daily Mean Total Canal Discharge (cfs)"},
{"count":3,"code":"IN_G","name":"Daily Mean Computed Gross Inflow (cfs)"},
{"count":3,"code":"IG","name":"Daily Gain (cfs)"},
{"count":3,"code":"FD","name":"Daily Mean Forebay Elevation (feet)"},
{"count":3,"code":"AF_ACT","name":"Reservoir Active Storage Content (acre-feet)"},
{"count":2,"code":"V3","name":"Unit No. 3 Hourly Generation (gwh)"},
{"count":2,"code":"V2","name":"Unit No. 2 Hourly Generation (gwh)"},
{"count":2,"code":"V1","name":"Unit No. 1 Hourly Generation (gwh)"},
{"count":2,"code":"RFD","name":"Daily Mean Gate #6 Opening (feet)"},
{"count":2,"code":"R_BP","name":"Bypass Opening (% open)"},
{"count":2,"code":"RBID","name":"Daily Mean Gate #2 Opening (inches)"},
{"count":2,"code":"RAID","name":"Daily Mean Gate #1 Opening (inches)"},
{"count":2,"code":"QJW","name":"Daily Mean West Canal Discharge (cfs)"},
{"count":2,"code":"QD_BAL","name":"Flow in Excess or Deficit [-] of Canadian Share (cfs)"},
{"count":2,"code":"QBP","name":"Daily Mean River Bypass (cfs)"},
{"count":2,"code":"PSAT","name":"Percent Total Saturation (percent)"},
{"count":2,"code":"PSATMX","name":"????"},
{"count":2,"code":"PSATMN","name":"????"},
{"count":2,"code":"PP_EFF","name":"Powerplant Efficiency (percent)"},
{"count":2,"code":"MW3","name":"Unit #3 Daily Generation (mwh)"},
{"count":2,"code":"MW2","name":"Unit #2 Daily Generation (mwh)"},
{"count":2,"code":"MW1","name":"Unit #1 Daily Generation (mwh)"},
{"count":2,"code":"GAIN","name":"Daily River Basin Gain between designated stations (cfs)"},
{"count":2,"code":"FB_M","name":"Reservoir Forebay Elevation (meters)"},
{"count":2,"code":"CFSPL","name":"Canyon Ferry Total Spillway Discharge (cfs) (SCADA)"},
{"count":2,"code":"CFS_MW","name":"CFS per Megawatt (cfs) (SCADA)"},
{"count":2,"code":"CFHVP","name":"Helena Valley Pump Discharge (cfs) (SCADA)"},
{"count":2,"code":"CFHVE","name":"Helena Valley Turbine Discharge (cfs) (SCADA)"},
{"count":1,"code":"XG","name":"Maximum 4 inch soil temp (degrees F)"},
{"count":1,"code":"XC","name":"Minimum 4 inch soil temp (degrees F)"},
{"count":1,"code":"VT_SP","name":"Total Spirit Mountain Powerplant Daily Energy Generation (mwh)"},
{"count":1,"code":"VT_SH","name":"Total Shoshone Powerplant Daily Energy Generation (mwh)"},
{"count":1,"code":"VT_HM","name":"Total Heart Mountain Powerplant Daily Energy Generation (mwh)"},
{"count":1,"code":"VT_BB","name":"Total Buffalo Bill Powerplant Daily Energy Generation (mwh)"},
{"count":1,"code":"V4","name":"Unit No. 4 Hourly Generation (gwh)"},
{"count":1,"code":"USQD","name":"Daily Total US Share at Eastern Crossing (cfs)"},
{"count":1,"code":"TWMX","name":"Daily Maximum Tailwater Elevation (feet)"},
{"count":1,"code":"TWMN","name":"Daily Minimum Tailwater Elevation (feet)"},
{"count":1,"code":"(Timestamps","name":"other than 0000 hours are shown following parameter names)"},
{"count":1,"code":"STMB_QD","name":"St. Mary River at Boundary Discharge (cfs)"},
{"count":1,"code":"SP1_MIN","name":"Daily Minimum System Pressure Gage #1 (psi)"},
{"count":1,"code":"SP1_MAX","name":"Daily Maximum System Pressure Gage #1 (psi)"},
{"count":1,"code":"SP1_AVG","name":"Daily Mean System Pressure Gage #1 (psi)"},
{"count":1,"code":"SMEDPSI","name":"Water Pressure used to Determine Head on Spirit Mtn (psi)"},
{"count":1,"code":"SEBH","name":"Snow Water Equivalent Bighorn Drainage (inches)"},
{"count":1,"code":"SEBH_PC","name":"Snow Water Equivalent Percent Ave Bighorn Drainage(percnt)"},
{"count":1,"code":"SEBHB","name":"Snow Water Equivalent Bighorn Subdrainage (inches)"},
{"count":1,"code":"SEBHB_P","name":"Snow Water Equivalent Percent Ave Bighorn Subdrainage(percnt)"},
{"count":1,"code":"SEBH_AV","name":"Snow Water Equivalent Average Bighorn Drainage (inches)"},
{"count":1,"code":"RHD","name":"Daily Mean Gate #8 Opening (feet)"},
{"count":1,"code":"RG8D","name":"Regulating Gate No. 8 Daily Average Opening (feet)"},
{"count":1,"code":"RG7D","name":"Regulating Gate No. 7 Daily Average Opening (feet)"},
{"count":1,"code":"RG6D","name":"Regulating Gate No. 6 Daily Average Opening (feet)"},
{"count":1,"code":"RG5D","name":"Regulating Gate No. 5 Daily Average Opening (feet)"},
{"count":1,"code":"RG4D","name":"Regulating Gate No. 4 Daily Average Opening (feet)"},
{"count":1,"code":"RG3D","name":"Regulating Gate No. 3 Daily Average Opening (feet)"},
{"count":1,"code":"RG2D","name":"Regulating Gate No. 2 Daily Average Opening (feet)"},
{"count":1,"code":"RG1D","name":"Regulating Gate No. 1 Daily Average Opening (feet)"},
{"count":1,"code":"RED","name":"Daily Mean Gate #5 Opening (feet)"},
{"count":1,"code":"R4GHD","name":"Daily Mean Gate No. 4 Opening (feet)"},
{"count":1,"code":"R2GHD","name":"Daily Mean Gate No. 2 Opening (feet)"},
{"count":1,"code":"QVJF","name":"Discharge through the Jet Flow Gate (cfs)"},
{"count":1,"code":"QV4X5","name":"Discharge through the 4 by 5 Gates (cfs)"},
{"count":1,"code":"QUX","name":"Daily Mean Computed Unregulated USGS Flow (cfs)"},
{"count":1,"code":"QUD_US","name":"United States share of natural flow (cfs)"},
{"count":1,"code":"QUD_CAN","name":"Canadian share of natural flow (cfs)"},
{"count":1,"code":"QSPG","name":"Inflow to Shoshone River from springs above SRBB gage (cfs)"},
{"count":1,"code":"QRNEWD","name":"Daily Mean River Discharge Using New Equation (cfs)"},
{"count":1,"code":"QRIVS","name":"Daily Mean Release to Shoshone w/o Springs (cfs)"},
{"count":1,"code":"QRIV","name":"Daily Mean Flow at River Gage (cfs)"},
{"count":1,"code":"QPHVD","name":"Daily Mean Discharge Pumped to Helena Valley (cfs)"},
{"count":1,"code":"QNEWD","name":"Daily Mean Total Discharge Using New Equation(cfs)"},
{"count":1,"code":"QNAT","name":"Daily Total Natural Flow at Eastern Crossing (cfs)"},
{"count":1,"code":"QJ_WCFC","name":"Daily Willow Creek Feeder Canal Discharge (cfs)"},
{"count":1,"code":"QJU","name":"Daily Mean Upper Lucerne Canal Discharge (cfs)"},
{"count":1,"code":"QJ_PSC","name":"Daily Pishkun Supply Canal Discharge (cfs)"},
{"count":1,"code":"QJNEWD","name":"Daily Mean Canal Discharge Using New Equation(cfs)"},
{"count":1,"code":"QJM","name":"Daily Mean Madden Lateral Discharge (cfs)"},
{"count":1,"code":"QJLW","name":"Daily Mean Lower Lucerne Canal Discharge (cfs)"},
{"count":1,"code":"QJI","name":"Canal Inflow (cfs)"},
{"count":1,"code":"QJG","name":"????"},
{"count":1,"code":"QJETD","name":"Daily Mean Discharge Jet Gates (cfs)"},
{"count":1,"code":"QJE","name":"Daily Mean East Canal Discharge (cfs)"},
{"count":1,"code":"QJD","name":"????"},
{"count":1,"code":"QITL","name":"Interstate Canal, total flow (cfs)"},
{"count":1,"code":"Q_FH","name":"Discharge, Fish Hatchery (cfs)"},
{"count":1,"code":"QESPD","name":"Daily Mean Power Turbine Discharge, Spirit Mtn (cfs)"},
{"count":1,"code":"QESD","name":"Daily Mean Power Turbine Discharge, Shoshone (cfs)"},
{"count":1,"code":"QEHVD","name":"Daily Mean Turbine Discharge for Helena Valley (cfs)"},
{"count":1,"code":"QEHD","name":"Daily Mean Power Turbine Discharge, Heart Mtn (cfs)"},
{"count":1,"code":"QEBBD","name":"Daily Mean Power Turbine Discharge, Buffalo Bill (cfs)"},
{"count":1,"code":"QD_NAT","name":"Daily Mean Total Milk River Natural Flow below Fresno (cfs)"},
{"count":1,"code":"QD_HOLM","name":"Daily Mean AF.QD HOLM (cfs)"},
{"count":1,"code":"QD_BLCK","name":"Daily Mean AF.QD WRCH Minus AF.QD BLCK (cfs)"},
{"count":1,"code":"QD_AF","name":"Daily Mean Total Discharge (acre-feet)"},
{"count":1,"code":"QD1","name":"Alternate Daily Mean Total Discharge (cfs)"},
{"count":1,"code":"QA27","name":"Interstate Canal, flow above milepost 2.7 (cfs)"},
{"count":1,"code":"OG2D","name":"Orifice Gate No. 2 Daily Average Opening (feet)"},
{"count":1,"code":"OG1D","name":"Orifice Gate No. 1 Daily Average Opening (feet)"},
{"count":1,"code":"OBTM","name":"Air Temperature Tunnel Sherburne (degrees F)"},
{"count":1,"code":"OBGM","name":"Air Temperature Gate Chamber Sherburne (degrees F)"},
{"count":1,"code":"MW4","name":"Unit #4 Daily Generation (mwh)"},
{"count":1,"code":"MRECQD","name":"Daily Total Flow at Eastern Crossing (cfs)"},
{"count":1,"code":"INMD","name":"Daily Mean Measured Inflow (cfs)"},
{"count":1,"code":"IND_NAT","name":"Daily Mean Natural Inflow (cfs)"},
{"count":1,"code":"HD_DIFF","name":"Daily Average CHO Head Differential (feet)"},
{"count":1,"code":"GJW","name":"Daily Mean West Canal Gage Height (feet)"},
{"count":1,"code":"GJU","name":"Daily Mean Upper Lucerne Canal Gage Height (feet)"},
{"count":1,"code":"GJT","name":"Daily Mean Canal Gage Height for Turnout (feet)"},
{"count":1,"code":"GJS","name":"????"},
{"count":1,"code":"GJN","name":"????"},
{"count":1,"code":"GJM","name":"Daily Mean Madden Lateral Gage Height (feet)"},
{"count":1,"code":"GJLW","name":"Daily Mean Lower Lucerne Canal Gage Height (feet)"},
{"count":1,"code":"GJE","name":"Daily Mean East Canal Gage Height (feet)"},
{"count":1,"code":"GD2","name":"Alternate Daily Average Gage Height from RADAR (feet)"},
{"count":1,"code":"GAINEQA","name":"????"},
{"count":1,"code":"GAIN2","name":"Daily River Basin Gain between BBR/BOYR and BHR (cfs)"},
{"count":1,"code":"FX","name":"Daily Maximum Forebay Elevation (feet)"},
{"count":1,"code":"FN","name":"Daily Minimum Forebay Elevation (feet)"},
{"count":1,"code":"FB_MTER","name":"Reservoir Elevation, Mt. Elbert (feet)"},
{"count":1,"code":"FB_CHG","name":"Maximum Change in Forebay Elevation (feet)"},
{"count":1,"code":"DV_HM","name":"Diversion from Highline Canal to Lake Minatare, NE"},
{"count":1,"code":"CP1_MIN","name":"Daily Mimimum Cylinder Pressure Gage #1 (psi)"},
{"count":1,"code":"CP1_MAX","name":"Daily Maximum Cylinder Pressure Gage #1 (psi)"},
{"count":1,"code":"CP1_AVG","name":"Daily Mean Cylinder Pressure Gage #1 (psi)"},
{"count":1,"code":"CO","name":"Air Temperature (degrees C)"},
{"count":1,"code":"CHR","name":"Gate Open - Right (feet)"},
{"count":1,"code":"CHL","name":"Gate Open - Left (feet)"},
{"count":1,"code":"CFSP4","name":"Canyon Ferry Spillway Gate No. 4 Discharage (cfs) (SCADA)"},
{"count":1,"code":"CFSP3","name":"Canyon Ferry Spillway Gate No. 3 Discharage (cfs) (SCADA)"},
{"count":1,"code":"CFSP2","name":"Canyon Ferry Spillway Gate No. 2 Discharage (cfs) (SCADA)"},
{"count":1,"code":"CFSP1","name":"Canyon Ferry Spillway Gate No. 1 Discharage (cfs) (SCADA)"},
{"count":1,"code":"CFRVT","name":"Canyon Ferry River Outlet Total Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFRV","name":"Canyon Ferry River Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFRV4","name":"Canyon Ferry River Outlet Gate No. 4 Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFRV3","name":"Canyon Ferry River Outlet Gate No. 3 Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFRV2","name":"Canyon Ferry River Outlet Gate No. 2 Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFRV1","name":"Canyon Ferry River Outlet Gate No. 1 Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFQR","name":"Canyon Ferry River Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFQEM","name":"Canyon Ferry Total Acoustic Meter Turbine Discharge (cfs) (SCADA)"},
{"count":1,"code":"CFQ","name":"Canyon Ferry Total Discharge (cfs) (SCADA)"},
{"count":1,"code":"BY_PASS","name":"Sun River Diversion Dam Bypass (cfs)"},
{"count":1,"code":"BHQRD","name":"????"},
{"count":1,"code":"BHQEM","name":"Yellowtail Total Acoustic Turbine Discharge (cfs) (SCADA)"},
{"count":1,"code":"BHQEM4","name":"Yellowtail Acoustic Turbine No. 4 Discharge (cfs) (SCADA)"},
{"count":1,"code":"BHQEM3","name":"Yellowtail Acoustic Turbine No. 3 Discharge (cfs) (SCADA)"},
{"count":1,"code":"BHQEM2","name":"Yellowtail Acoustic Turbine No. 2 Discharge (cfs) (SCADA)"},
{"count":1,"code":"BHQEM1","name":"Yellowtail Acoustic Turbine No. 1 Discharge (cfs) (SCADA)"},
{"count":1,"code":"BBJV","name":"Buffalo Bill Jetflow Valve (percent open) (SCADA)"},
{"count":1,"code":"BB4X5S","name":"Buffalo Bill South 4X5 Gate (feet) (SCADA)"},
{"count":1,"code":"BB4X5N","name":"Buffalo Bill North 4X5 Gate (feet) (SCADA)"},
{"count":1,"code":"AF_T_M","name":"Reservoir Storage Content, Twin Lakes and Mt Elbert (acre-feet)"},
{"count":1,"code":"AF_MTER","name":"Reservoir Storage Content, Mt. Elbert (acre-feet)"},
{"count":1,"code":"AF_IN","name":"Daily Mean Computed Inflow (acre-feet)"},
{"count":1,"code":"ABAF","name":"Yellowtail Afterbay storage content (acre-feet) (SCADA)"}
];
